shallow_clone: true

os:
  - Visual Studio 2019

environment:
  matrix:
  - TOOLSET: vs2017
#  - TOOLSET: vs2019

platform:
# - Win32
  - x64

configuration:
# - Debug
  - Release

install:
  - git clone --depth 1 https://github.com/bkaradzic/bx ..\bx
  - git clone --depth 1 https://github.com/bkaradzic/bimg ..\bimg
  - ..\bx\tools\bin\windows\genie --with-tools --with-examples %TOOLSET%

build:
  project: .build/projects/$(TOOLSET)/bgfx.sln

after_build:
  - cd \projects\bgfx\.build\win64_vs2017\
  - 7z a -r \Projects\bgfx\bgfx-bins.zip bin
  - cd \projects\bgfx\examples\
  - 7z a -r \Projects\bgfx\bgfx-bins.zip runtime
# - dir /s /b c:\projects\

artifacts:
  - path: bgfx-bins.zip
    name: bgfx_bins
